name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Packing
      run: |
        mkdir dist
        cd src
        zip -r ../dist/Microsoft-Reward-Chrome-Ext-CN.zip .
        cd ..
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with: 
        path: dist/Microsoft-Reward-Chrome-Ext-CN.zip
    
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_PERSONNAL_TOKEN }}"
        automatic_release_tag: ${{ github.run_number }}-${{ github.sha }}
        prerelease: false
        files: |
          dist/Microsoft-Reward-Chrome-Ext-CN.zip